name: Compile LaTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Cache Tikz graphics
        uses: actions/cache@v2
        with:
          key: tikz
          path: "**/tikz"
      - name: Compile LaTeX document
        uses: ./.github/actions/latex
      - name: Upload files to Google Drive
        uses: PeronTheDuck/glob-to-drive@v2
        with:
          glob: "**/*.pdf"
          uploadTo: ${{ secrets.UPLOADTO }}
          credentials: ${{ secrets.CREDENTIALS }}
          token: ${{ secrets.TOKEN }}
          mimeType: "application/pdf"
